### ISSUE TITLE
PlayByFrame.arproj not working

### ISSUE THREAD

**Issue by fpscan** [juanmv94/SparkAR-FaceTrackingRecording#1]
Is it just me that sample project is not working?
![image](https://user-images.githubusercontent.com/4651944/75589970-443da280-5a8d-11ea-86f6-c221708a4406.png)

**Comment by fpscan** [comment]
and this is what it says with Record project

JavaScript error: Error: ./script.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):



SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
 @ multi ./script.js main[0] {
  "message": ".\/script.js\nModule build failed (from .\/node_modules\/babel-loader\/lib\/index.js):\n\n\n\nSyntaxError: Invalid or unexpected token\n    at Module._compile (internal\/modules\/cjs\/loader.js:895:18)\n    at Object.Module._extensions..js (internal\/modules\/cjs\/loader.js:995:10)\n    at Module.load (internal\/modules\/cjs\/loader.js:815:32)\n    at Function.Module._load (internal\/modules\/cjs\/loader.js:727:14)\n    at Module.require (internal\/modules\/cjs\/loader.js:852:19)\n    at require (internal\/modules\/cjs\/helpers.js:74:18)\n    at Module._compile (internal\/modules\/cjs\/loader.js:959:30)\n    at Object.Module._extensions..js (internal\/modules\/cjs\/loader.js:995:10)\n    at Module.load (internal\/modules\/cjs\/loader.js:815:32)\n @ multi .\/script.js main[0]",
  "line": 1,
  "expressionBeginOffset": 771,
  "expressionEndOffset": 771,
  "sourceId": 2382757238944,
  "sourceURL": "file:\/\/\/"
}

**Comment by juanmv94** [comment]
Project is working fine.
It seems that you have some issues with your Node internal libraries needed to execute script based projects. I had that problem once, caused by diferent Spark version installations, and to solve it I just 
 had to uninstall and reinstall SparkAR.
