### ISSUE TITLE
Can we do more accurate tracking using higher frames?

### ISSUE THREAD

**Issue by sanaa-syed268** [juanmv94/SparkAR-FaceTrackingRecording#3]
Can we do more accurate tracking using higher frames, but apply it to an animation sequence texture with a lower frame rate?
Lower frame rate video for keeping the file size smaller for a long video.

**Comment by juanmv94** [comment]
Yes, you can use the `ffmpeg -i input.mp4 -r XX %04d.jpg` command with diferent rates -r, one for record project facetracking, and the other one at a lower framerate for play project sequence.
Then you need to customize player code. Ex: replace the line `animationSequence.currentFrame=frame;` with something like `animationSequence.currentFrame=Math.floor(frame/2)` with facetracking having double framerate than animation.
