### ISSUE TITLE
How to improve the quality of the frames?

### ISSUE THREAD

**Issue by FrnklyN** [juanmv94/SparkAR-FaceTrackingRecording#4]
Is there a way to improve the quality of the frame a bit? I mean not to much because of the file sizes but I need a little bit more pixels 😄

**Comment by juanmv94** [comment]
You can use ffmpeg -q:v parameter to tune JPG compression (2=best quality, 31=worst quality). And well, you can obviously scale down the resolution if you want, but incrementing it is not good idea since that will not increase the quality, and it will increase file sizes.
